Implement pre-commits
quantori/edema-quantification pull request #12
Opened 2022-12-26 13:22 UTC by ViacheslavDanilov

2022-12-26 13:26 UTC, ViacheslavDanilov commented
@ryndovaira @mak-en @trioxane 

I implemented pre-commits allowing us to use the same standards during coding. Please have a look at the pre-commit pipeline described at: 

1. https://pre-commit.com/index.html
2. https://towardsdatascience.com/4-pre-commit-plugins-to-automate-code-reviewing-and-formatting-in-python-c80c6d2e9f5

2022-12-28 18:13 UTC, ryndovaira submitted a review, later dismissed

2022-12-29 18:25 UTC, mak-en requested changes

2022-12-29 18:25 UTC, mak-en commented on pyproject.toml
> +ignore-init-module = false
true

2023-01-02 12:35 UTC, ViacheslavDanilov commented
@mak-en 

Please check the replacement of **interrogate** with **pydocstyle**

2023-01-02 12:39 UTC, ViacheslavDanilov commented
@ryndovaira @mak-en 

No worries about merge conflicts. I will resolve them by myself.

2023-01-02 17:06 UTC, ViacheslavDanilov commented on pyproject.toml
> +fail-under = 50
Fixed

2023-01-02 17:06 UTC, ViacheslavDanilov commented on pyproject.toml
> +ignore-semiprivate = false
Fixed

2023-01-02 17:07 UTC, ViacheslavDanilov commented on pyproject.toml
> +ignore-private = false
Fixed

2023-01-02 17:07 UTC, ViacheslavDanilov commented on pyproject.toml
> +ignore-nested-functions = false
Fixed

2023-01-02 17:07 UTC, ViacheslavDanilov commented on pyproject.toml
> +ignore-nested-classes = true
Fixed

2023-01-02 17:07 UTC, ViacheslavDanilov commented on pyproject.toml
> +ignore-setters = false
Fixed

2023-01-02 17:07 UTC, ViacheslavDanilov commented on .pre-commit-config.yaml
> +# pylint
Fixed

2023-01-02 17:07 UTC, ViacheslavDanilov commented on pyproject.toml
> +ignore-init-module = false
Fixed

2023-01-02 17:07 UTC, ViacheslavDanilov commented on pyproject.toml
> +ignore-magic = false
Fixed

2023-01-02 17:09 UTC, ViacheslavDanilov commented
> @ryndovaira @mak-en
> 
> No worries about merge conflicts. I will resolve them by myself.

Resolved

2023-01-02 23:32 UTC, mak-en reviewed
Looks good!

2023-01-02 23:40 UTC, mak-en commented
> 

I am on that

2023-01-03 12:20 UTC, mak-en submitted a review, later dismissed

2023-01-03 14:06 UTC, merged