Dry run different models
quantori/edema-quantification pull request #23
Opened 2023-04-18 17:57 UTC by ryndovaira

2023-04-18 21:29 UTC, ViacheslavDanilov requested changes
@ryndovaira 

Do this first 😊

`pre-commit install`
`pre-commit run --all-files --verbose`

Then

`git commit...`
`git push...`

2023-04-19 18:55 UTC, ryndovaira commented
@ViacheslavDanilov it has a lot of errors in the datasets directory. For example
```
src\models\mmdetection\mmdet\datasets\voc.py:13: error: Incompatible types in assignment (expression has type "Tuple[str, str, str, str, str, str, str, str, str, str, str, str, str, str, str, str, str, str, str, str]", base class "CustomDataset" 
defined the type as "None")  [assignment]
src\models\mmdetection\mmdet\datasets\voc.py:36: error: Incompatible types in assignment (expression has type "List[Tuple[int, int, int]]", base class "CustomDataset" defined the type as "None")  [assignment]
Found 71 errors in 32 files (checked 422 source files)
```
What should I do?

2023-04-21 15:42 UTC, ViacheslavDanilov commented on src/models/mmdetection/tools/train.py
> +            print(f'\nError: {ex}')
@ryndovaira 

`print(f'\nError: {ex}') ` -  правильно я понимаю, что это абстрактный принт? То есть когда мы зайдём на эту ветку, то дальше обучения в целом никакого не будет?

2023-04-21 15:42 UTC, ViacheslavDanilov commented on src/models/mmdetection/tools/train.py
> +        #     ml_flow_logger['params']['params'] = 'NA'
Это не работает, но мы пока оставляем на будущее?

2023-04-21 15:43 UTC, ViacheslavDanilov submitted a review, later dismissed

2023-04-21 17:49 UTC, ryndovaira commented on src/models/mmdetection/tools/train.py
> +            print(f'\nError: {ex}')
да, обучения дальше не будет

2023-04-21 17:49 UTC, ryndovaira commented on src/models/mmdetection/tools/train.py
> +            print(f'\nError: {ex}')
и да, надо это исправить

2023-04-21 17:49 UTC, ryndovaira commented on src/models/mmdetection/tools/train.py
> +        #     ml_flow_logger['params']['params'] = 'NA'
да, давай оставим

2023-04-21 17:52 UTC, ViacheslavDanilov commented on src/models/mmdetection/tools/train.py
> +            print(f'\nError: {ex}')
Как-раз зальёшь новый фикс и посмотрим как пройдут все чеки.

2023-04-24 09:34 UTC, ViacheslavDanilov approved these changes
LGTM

2023-04-24 09:34 UTC, merged