Implement edema severity classifier.
quantori/edema-quantification pull request #49
Opened 2023-06-15 15:25 UTC by mak-en

2023-06-15 18:33 UTC, ViacheslavDanilov commented on src/models/classifier.py
> +        """Called when edma severity needs to be classified."""
@mak-en мы можем пока не усложнять и не использовать этот базовый абстрактный класс? Пока сомневаюсь, что у нас появится, какой-то другой классификатор.

2023-06-15 18:34 UTC, ViacheslavDanilov commented on src/models/classifier.py
> +        """The main classification function.
@mak-en в свою очередь, предлагаю переименовать этот класс в **EdemaClassifier** и убрать наследование.

2023-06-15 18:37 UTC, ViacheslavDanilov requested changes
NACK: I need PR to **edema_pipeline** instead of main

2023-06-16 08:36 UTC, mak-en commented on src/models/classifier.py
> +        """The main classification function.
Слав, как ты желтым мое имя выделяешь?

2023-06-16 11:00 UTC, ViacheslavDanilov commented on src/models/classifier.py
> +            edema_severity, feature, confidence = EdemaClassifier._get_edema_severity(df_img)
@mak-en 

1. Make sure that we may process empty data frames.
2. Addition of class ID and class should be enough.

2023-06-16 11:01 UTC, ViacheslavDanilov commented on src/models/classifier.py
> +        df_out = pd.DataFrame(self._output)
@mak-en please keep the source detections as well

2023-06-16 11:03 UTC, ViacheslavDanilov requested changes
NACK: minor changes needed + PR should be merged into **edema_pipeline**

2023-06-16 19:47 UTC, ViacheslavDanilov approved these changes
LGTM

2023-06-16 19:47 UTC, merged